### ISSUE TITLE
Testing the calendar before december 1st

### ISSUE THREAD

**Issue by mharst** [nschreder/powerappadventcalendar#1]
Hi N. Schreder,

I'm quite new to powerapps. Is it possible to test if the numbers work before december 1st?
When I try to open one number nothing happens.

**Comment by nschreder** [comment]
Hi! This design is by default. However, you can change the Excel file which contains all the content and adjust the date to test it. E.g., 1st of December is then 1st of November.

**Comment by mharst** [comment]
Thank you, that worked! ;) 
Happy holidays
